import { regression, documentation, performance } from './extendedContent.js';

// Educational snippets are display-only. They are never executed.
const bugs = [
  {
    title: 'The missing birthday',
    description: 'Check an age boundary before a customer is turned away.',
    prompt: 'Requirement: customers aged 18 or older may register. Select every defect in this implementation.',
    code: 'function canRegister(age) {\n  return age > 18;\n}',
    options: ['An 18-year-old is incorrectly rejected.', 'A 19-year-old is incorrectly rejected.', 'The comparison must include equality.', 'The function needs a loop.'],
    answers: [0, 2],
    explanation: '“18 or older” includes 18, so the predicate must be age >= 18. Boundary-value tests at 17, 18, and 19 expose the defect; adding a loop does not help.',
  },
  {
    title: 'A cart that forgets',
    description: 'Trace a shopping-cart total through a loop.',
    prompt: 'Prices are positive integer cents. A cart total must include every item. Select every true defect.',
    code: 'function total(prices) {\n  let sum = 0;\n  for (let i = 0; i < prices.length - 1; i++) {\n    sum += prices[i];\n  }\n  return sum;\n}',
    options: ['The last item is never added.', 'A one-item cart incorrectly totals zero.', 'An empty cart must throw instead of returning zero.', 'Using integer cents causes rounding errors.'],
    answers: [0, 1],
    explanation: 'The loop stops one index early. Use i < prices.length. Empty, one-item, and multiple-item carts are distinct equivalence classes; integer cents avoid ordinary decimal rounding issues.',
  },
  {
    title: 'The generous coupon',
    description: 'Find a Boolean logic bug in a promotion.',
    prompt: 'A discount requires BOTH a premium membership and a subtotal of at least 5000 cents. Select all defects.',
    code: 'function getsDiscount(isPremium, subtotal) {\n  return isPremium || subtotal >= 5000;\n}',
    options: ['A non-premium customer spending 5000 qualifies incorrectly.', 'A premium customer spending 100 qualifies incorrectly.', 'A premium customer spending 5000 is rejected.', 'The subtotal comparison should be strictly greater than 5000.'],
    answers: [0, 1],
    explanation: 'OR admits either condition alone. AND is required. A four-row decision table for membership and spending threshold tests the policy, including the inclusive 5000 boundary.',
  },
  {
    title: 'Sorting by surprise',
    description: 'Inspect numeric ordering and hidden mutation.',
    prompt: 'Requirement: return prices in ascending numeric order without modifying the input array. Select all defects.',
    code: 'function sortedPrices(prices) {\n  return prices.sort();\n}',
    options: ['Default sorting can place 100 before 20.', 'The caller’s array is modified in place.', 'The result is always descending.', 'The function cannot accept a one-element array.'],
    answers: [0, 1],
    explanation: 'JavaScript sort() compares string representations by default and mutates its receiver. Copy first and use a numeric comparator: [...prices].sort((a, b) => a - b). Test both order and input preservation.',
  },
  {
    title: 'Loading forever',
    description: 'Follow a request through success and failure.',
    prompt: 'The loading indicator must stop after success OR failure, and HTTP errors must show an error message. Select every true finding or correction.',
    code: 'async function loadProfile() {\n  setLoading(true);\n  try {\n    const response = await fetch("/profile");\n    const profile = await response.json();\n    setProfile(profile);\n    setLoading(false);\n  } catch {\n    setError("Could not load");\n  }\n}',
    options: ['A network failure leaves loading true.', 'HTTP 500 is not explicitly checked and may be displayed as a profile.', 'Calling response.json() is always synchronous.', 'A finally block could ensure loading is reset.'],
    answers: [0, 1, 3],
    explanation: 'fetch rejects on network errors, not ordinary HTTP error statuses. Check response.ok and reset loading in finally so both success and failure paths terminate the spinner.',
  },
  {
    title: 'Yesterday in another zone',
    description: 'Separate UTC dates from local calendar dates.',
    prompt: 'A check-in streak is defined by UTC calendar day for all users. Select all issues with this implementation.',
    code: 'function dayKey(date) {\n  return `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`;\n}\nfunction isNextDay(previous, current) {\n  return current - previous === 24 * 60 * 60 * 1000;\n}',
    options: ['Local date getters can assign different day keys to the same instant.', 'Consecutive UTC days do not require check-ins exactly 24 hours apart.', 'UTC dates depend on the player’s language.', 'The code needs UTC day keys rather than exact elapsed-hour equality.'],
    answers: [0, 1, 3],
    explanation: 'Use a UTC calendar key such as ISO date and compare day numbers. A 23:59 UTC check-in followed by 00:01 UTC is a consecutive day even though only two minutes elapsed.',
  },
  {
    title: 'The double booking',
    description: 'Find a race in the last-seat reservation flow.',
    prompt: 'There is one remaining seat. Two requests may run concurrently. Select every real issue or necessary correction.',
    code: 'async function reserve(eventId, userId) {\n  const event = await db.getEvent(eventId);\n  if (event.seats > 0) {\n    await db.insertReservation(eventId, userId);\n    await db.setSeats(eventId, event.seats - 1);\n    return "reserved";\n  }\n  return "sold out";\n}',
    options: ['Both requests can observe one seat and both reserve it.', 'Checking seats only in the browser would solve the race.', 'Seat decrement and reservation must be an atomic, concurrency-safe operation.', 'Using await automatically serializes all incoming requests.'],
    answers: [0, 2],
    explanation: 'A read-check-write sequence races across requests. Use a transaction with an appropriate lock or conditional decrement and commit the reservation atomically. await sequences one function, not all callers.',
  },
  {
    title: 'An invoice for anyone',
    description: 'Distinguish authentication from object authorization.',
    prompt: 'Only an invoice’s owner may view it. Assume requireLogin correctly authenticates the session and ids are bound SQL parameters. Select all security defects.',
    code: 'app.get("/invoice/:id", requireLogin, async (req, res) => {\n  const invoice = await db.getInvoice(req.params.id);\n  res.json(invoice);\n});',
    options: ['There is no check that the invoice belongs to the session user.', 'Knowing another invoice id may expose another customer’s data.', 'Parameterized queries alone enforce ownership.', 'Requiring login makes ownership checks unnecessary.'],
    answers: [0, 1],
    explanation: 'Authentication says who the caller is; authorization says which records they may access. Scope the lookup to both invoice id and session user id, and test two authenticated accounts against each other’s invoices.',
  },
  {
    title: 'Paid twice',
    description: 'Inspect retry behavior in a payment workflow.',
    prompt: 'A client may retry a payment after a timeout. Each order must be charged at most once. Select all defects or required protections.',
    code: 'async function pay(order) {\n  const charge = await gateway.charge(order.total);\n  await db.markPaid(order.id, charge.id);\n  return charge;\n}',
    options: ['A timeout after a successful charge can lead to a second charge on retry.', 'A stable order-based idempotency key at the gateway is needed.', 'Generating a new idempotency key for every retry prevents duplicates.', 'Concurrent requests also need an atomic order payment-state transition.'],
    answers: [0, 1, 3],
    explanation: 'Retries can repeat a side effect even when the first response is lost. Reuse a stable idempotency key and coordinate order state atomically. Test response loss after charging and simultaneous payment requests.',
  },
  {
    title: 'The stale search winner',
    description: 'Trace out-of-order asynchronous responses.',
    prompt: 'Search results must always correspond to the latest typed query. Select every valid issue or fix.',
    code: 'async function onQueryChanged(query) {\n  const response = await fetch("/search?q=" + encodeURIComponent(query));\n  const results = await response.json();\n  renderResults(results);\n}',
    options: ['A slow response for an earlier query can overwrite the latest results.', 'A request sequence number checked before rendering prevents stale updates.', 'URL encoding guarantees responses arrive in order.', 'Debouncing alone guarantees no older in-flight request can overwrite new results.'],
    answers: [0, 1],
    explanation: 'Network responses may complete out of order. Track the latest request identity and ignore older completions; cancellation can also reduce wasted work. Debouncing reduces request count but does not guarantee ordering.',
  },
];

const tests = [
  {
    title: 'Password boundaries',
    description: 'Choose a compact boundary-value test suite.',
    prompt: 'A password is valid when its length is 8 through 64 characters inclusive. All characters in these examples are allowed. Select the cases needed to cover both boundaries and their immediate invalid neighbors.',
    options: ['7 characters: rejected.', '8 characters: accepted.', '64 characters: accepted.', '65 characters: rejected.', '20 characters: rejected.'],
    answers: [0, 1, 2, 3],
    explanation: 'Boundary-value analysis checks just below, at, and just above each limit. The four cases are 7, 8, 64, and 65. A 20-character password is valid but does not test a limit.',
  },
  {
    title: 'Shipping decision table',
    description: 'Cover every combination of two business rules.',
    prompt: 'Shipping is free for premium customers OR orders of at least $50; otherwise it costs $5. Select all correctly specified cases needed for the full four-row decision table.',
    options: ['Premium, $20 order → free.', 'Premium, $50 order → free.', 'Standard, $20 order → $5.', 'Standard, $50 order → free.', 'Standard, $50 order → $5.'],
    answers: [0, 1, 2, 3],
    explanation: 'Two Boolean conditions produce four combinations. Cover premium/non-premium and below/at-threshold independently. The threshold is inclusive, so a standard $50 order ships free.',
  },
  {
    title: 'Search equivalence classes',
    description: 'Cover distinct input behaviors without redundant examples.',
    prompt: 'Search trims whitespace, ignores case, returns [] for an empty query, and returns [] for no matches. The catalog contains only “Tea”. Select every correctly specified case covering these behaviors.',
    options: ['" tea " → ["Tea"].', '"coffee" → ["Tea"].', '"" → [].', '"TEA" → [].', '"coffee" → [].', '"TEA" → ["Tea"].'],
    answers: [0, 2, 4, 5],
    explanation: 'Whitespace normalization, empty input, no match, and case normalization are different behavioral classes. A no-match query must not fall back to an unrelated product.',
  },
  {
    title: 'Cart state transitions',
    description: 'Test actions as a journey rather than isolated buttons.',
    prompt: 'Cart quantities must stay between 0 and available stock. Exceeding stock leaves quantity unchanged and displays an error. Removing the final unit removes the line. Stock is 2. Select all valid tests.',
    options: ['Adding a third unit should silently create quantity 3.', 'Add twice: quantity becomes 2.', 'Remove the only unit: line disappears.', 'Remove an absent product: quantity becomes -1.', 'Add a third time: quantity remains 2 and an error appears.'],
    answers: [1, 2, 4],
    explanation: 'State-transition coverage includes empty → one, one → full, full → rejected addition, and one → empty. Invalid transitions must preserve valid state, including removal of an absent item.',
  },
  {
    title: 'Upload gatekeeper',
    description: 'Test file validation beyond a friendly filename.',
    prompt: 'Uploads accept PNG files up to 2 MiB inclusive. The server checks the actual file signature, not just extension. Select all correctly specified tests.',
    options: ['Valid PNG exactly 2 MiB → accepted.', 'Any file ending .png → accepted regardless of bytes.', 'Valid PNG 2 MiB + 1 byte → rejected.', 'Valid PNG 1 byte below the limit → rejected.', 'Executable renamed photo.png → rejected.'],
    answers: [0, 2, 4],
    explanation: 'Cover the inclusive size boundary, its invalid neighbor, and a disguised file. A valid PNG below the limit is allowed. Client checks and filename extensions are insufficient; enforce size and format using server-side inspection.',
  },
  {
    title: 'Session lifecycle',
    description: 'Build a suite for login, logout, and expired sessions.',
    prompt: 'Private pages require a current server session. Logout revokes that session. Login errors must not reveal whether an email exists. Select all required tests with correct expectations.',
    options: ['Access a private endpoint without a cookie → unauthorized.', 'A cookie containing any user id grants access.', 'Reuse a session cookie after logout → unauthorized.', 'Unknown email and incorrect password produce the same generic login error.', 'Use an expired session → unauthorized.'],
    answers: [0, 2, 3, 4],
    explanation: 'Test unauthenticated, revoked, and expired states, plus non-enumerating failure messages. A cookie is a credential only when it is an unpredictable valid token verified by the server.',
  },
  {
    title: 'UTC streak midnight',
    description: 'Cover a day boundary without waiting a whole day.',
    prompt: 'A streak increments on the first successful challenge in each consecutive UTC day. Same-day repeats do not increment; skipping a day resets to 1. Select every correctly specified test.',
    options: ['Every elapsed hour increments the daily streak.', 'Two successes within the same UTC date → no second increment.', 'Success Monday then Wednesday, none Tuesday → reset to 1.', 'Success at 23:59 UTC then 00:01 UTC next day → increment.', 'Different device time zones at the same instant → same UTC day.'],
    answers: [1, 2, 3, 4],
    explanation: 'Use a controlled clock around UTC midnight. Check consecutive days, duplicate same-day actions, gaps, and independence from client time zone. The rule is calendar-based, not elapsed-time-based.',
  },
  {
    title: 'Pagination under pressure',
    description: 'Specify coverage for stable cursor pagination.',
    prompt: 'An API returns at most 20 items, ordered by (createdAt, id), with an exclusive cursor. Existing items must appear once even if a newer item is inserted between page requests. Select all appropriate tests.',
    options: ['21 existing items → first page has 20 and second has 1.', 'Page 2 should repeat the cursor item to ensure continuity.', 'Items with equal timestamps remain deterministic using id as tie-breaker.', 'Empty dataset → empty list and no next cursor.', 'Insert a newer item after page 1 → page 2 does not duplicate page-1 items.'],
    answers: [0, 2, 3, 4],
    explanation: 'Test the page-size boundary, total ordering, concurrent insertion, and empty results. An exclusive cursor excludes its own item. Stable cursor pagination avoids offset shifts caused by new items.',
  },
  {
    title: 'Retry-safe checkout',
    description: 'Cover failures on both sides of a payment response.',
    prompt: 'An order payment endpoint promises idempotency for the same key and rejects reuse of a key with a different amount. Select all tests needed for that contract.',
    options: ['Retry the same key and amount → original result, one charge.', 'Send the same key concurrently → one charge.', 'Retry with the same key → always create a second payment.', 'Lose the response after the gateway succeeds, then retry → one charge.', 'Reuse the same key with a different amount → conflict, no new charge.'],
    answers: [0, 1, 3, 4],
    explanation: 'Idempotency must cover sequential retries, concurrency, and uncertain outcomes after a side effect. Binding the key to request details prevents accidental reuse for a different payment.',
  },
  {
    title: 'A resilient release',
    description: 'Choose a risk-based regression suite for checkout.',
    prompt: 'A checkout release adds discount codes. Requirements: stock cannot oversell, an order is charged at most once, discounted totals have a floor of zero, and existing full-price checkout still works. Select every release-blocking test.',
    options: ['Only check that the new discount input has the right placeholder.', 'Full-price purchase without a code still completes correctly.', 'Two simultaneous buyers of the final unit cannot both reserve it.', 'Retry after a lost payment response does not charge twice.', 'Discount larger than subtotal produces a total of zero, not a negative charge.'],
    answers: [1, 2, 3, 4],
    explanation: 'Risk-based regression prioritizes money, stock integrity, backward compatibility, and new boundary rules. Cosmetic checks are useful but cannot replace tests of the critical business invariants.',
  },
];

export const challenges = [
  ...bugs.map((challenge, index) => makeChallenge(challenge, 'bugs', index)),
  ...tests.map((challenge, index) => makeChallenge(challenge, 'tests', index)),
  ...regression.map((challenge, index) => makeChallenge(challenge, 'regression', index)),
  ...documentation.map((challenge, index) => makeChallenge(challenge, 'documentation', index)),
  ...performance.map((challenge, index) => makeChallenge(challenge, 'performance', index)),
];

function makeChallenge(challenge, mode, index) {
  return {
    ...challenge,
    id: `${mode}-${index + 1}`,
    mode,
    level: index + 1,
    difficulty: index < 3 ? 'Beginner' : index < 7 ? 'Intermediate' : 'Advanced',
    durationSeconds: index < 3 ? 120 : index < 7 ? 150 : 180,
    options: challenge.options.map((text, i) => ({ id: `option-${i + 1}`, text })),
    answers: challenge.answers.map((i) => `option-${i + 1}`),
  };
}

export const challengeById = new Map(challenges.map((challenge) => [challenge.id, challenge]));

export const achievementDefinitions = [
  { id: 'first-clear', name: 'First Steps', description: 'Complete your first challenge.' },
  { id: 'bug-spotter', name: 'Bug Spotter', description: 'Complete five Bug Hunting challenges.' },
  { id: 'test-master', name: 'Test Master', description: 'Complete all ten Test Case Arena challenges.' },
  { id: 'speed-demon', name: 'Speed Demon', description: 'First-clear a challenge in under 30 seconds.' },
  { id: 'perfectionist', name: 'Perfectionist', description: 'Clear a challenge on your first submitted attempt.' },
  { id: 'seven-day-warrior', name: '7-Day Warrior', description: 'Complete challenges on seven consecutive UTC days.' },
  { id: 'quest-complete', name: 'Quest Complete', description: 'Complete all twenty challenges.' },
  { id: 'regression-master', name: 'Regression Master', description: 'Complete all fifteen Regression Roulette challenges.' },
  { id: 'documentation-detective', name: 'Documentation Detective', description: 'Complete all ten Documentation Detective challenges.' },
  { id: 'performance-patrol', name: 'Performance Patrol', description: 'Complete all ten Performance Patrol challenges.' },
  { id: 'all-domains', name: 'All Domains Champion', description: 'Complete all fifty-five challenges across five domains.' },
];
